WITH RECURSIVE TIME AS (
SELECT 0 AS HOUR UNION ALL SELECT HOUR+1 FROM TIME WHERE HOUR < 23)

SELECT HOUR, COUNT(DATETIME) AS COUNT FROM TIME LEFT JOIN ANIMAL_OUTS ON HOUR = HOUR(DATETIME) GROUP BY HOUR ORDER BY HOUR;